name: flutter_color_models
description: >-
  A wrapper for the color_models plugin with added
  support for Flutter's Color class.
version: 0.1.0+3
homepage: https://github.com/james-alex/flutter_color_models

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  color_models: ^0.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.1
