name: flutter_color_models
description: >-
  A set of classes representing the CMYK, HSI, HSL, HSP, HSV, LAB,
  RGB, and XYZ color spaces with methods to convert colors between
  each space.
version: 0.1.6
homepage: https://github.com/james-alex/flutter_color_models

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  color_models: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
