name: flutter_color_models
description: >-
  A set of classes representing the CMYK, HSI, HSL, HSP, HSV, LAB,
  RGB, and XYZ color spaces with methods to convert colors between
  each space.
version: 0.1.1+4
homepage: https://github.com/james-alex/flutter_color_models

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  color_models: ^0.2.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.1
